### ISSUE TITLE
Uncaught Error: Cannot find module "vue-inputmask"

### ISSUE THREAD

**Issue by waqasd4int** [captiz/vue-inputmask#1]
I am using `vue-inputmask` by import method but it give error :
`Uncaught Error: Cannot find module "vue-inputmask"`
```javascript
import Vue from 'vue'
var VueInputmask = require('vue-inputmask');
Vue.use(VueInputmask);
````

**Comment by scleriot** [comment]
Hi,
I'm not sure vue-inputmask can be used with **import**, I'll have a look!

Anyway in your example you're using require, so I'm not sure what the problem is?
