### ISSUE TITLE
Use with extensions?

### ISSUE THREAD

**Issue by andrewtweber** [captiz/vue-inputmask#2]
Can't get it to work with extensions.

If I try this, it seems to interpret the alias "currency" as the mask.

`<input v-mask="{alias: 'currency'}">`

I also tried copying the currency extension itself into the Vue component's data. Copied directly from [inputmask.numeric.extensions.js](https://github.com/RobinHerbots/Inputmask/blob/3.x/js/inputmask.numeric.extensions.js#L580)

```
data() {
  return {
    currency: {
      prefix: "$ ",
      groupSeparator: ",",
      alias: "numeric",
      placeholder: "0",
      autoGroup: true,
      digits: 2,
      digitsOptional: false,
      clearMaskOnLostFocus: false
    }
  }
}
```

And then

`<input v-mask="currency">`

But it's the same thing. It just uses the alias "numeric" as the mask, and ignores all of the other options.

**Comment by scleriot** [comment]
I see that you closed this issue, how did you fix your problem @andrewtweber ?

**Comment by stefancityuk** [comment]
I am also trying this same idea, I can't get it to work with aliases. @andrewtweber, how did you fix this?

**Comment by andrewtweber** [comment]
@stefancityuk I never got it working with this. I had to build my own directive, which uses some fishy code with the Vue internals, and is owned by my company so I can't really share it. Sorry
